rules:
  CallbackFuzz:
    description: Test for open redirects and potential SSRFs by checking for certain responses or callbacks to your server
    injections:
      - http://example.net
      - //example.net
      - https://company.com.example.net
      - "@example.net"
    expectation:
      responseContents:
        - Example Domain
  SqlInjectionCheck:
    description: Test for potential SQL injections by injecting characters to break SQL statements
    injections:
      - "'"
      - )
    expectation:
      responseCodes:
        - 500
  XssDetection:
    description: Test for XSS by discovering potentially unsanitized/encoded input in responses
    injections:
      - '"><h2>asd</h2>'
    expectation:
      responseContents:
        - '<h2>asd</h2>'
      responseHeaders:
        Content-Type: html
