rules:
  CallbackFuzz:
    description: Test for open redirects and potential SSRFs by checking for certain responses or callbacks to your server
    injections:
      - https://jl81tjsl8qle2l3w7803oyrq7hda1z.burpcollaborator.net
      - //jl81tjsl8qle2l3w7803oyrq7hda1z.burpcollaborator.net
      - https://n33ma.com.jl81tjsl8qle2l3w7803oyrq7hda1z.burpcollaborator.net
    expectation:
      responseContents:
        - a0aru8x5g9zt3w4lngnvk8zjlgz
  SqlInjectionCheck:
    description: Test for potential SQL injections by injecting characters to break SQL statements
    injections:
      - "'"
      - )
    expectation:
      responseCodes:
        - 500
  XssDetection:
    description: Test for XSS by discovering potentially unsanitized/encoded input in responses
    injections:
      - '"><h2>asd</h2>'
    expectation:
      responseContents:
        - '"><h2>asd</h2>'
      responseHeaders:
        Content-Type: html
